# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quiz.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sys


class Ui_QuizGame(object):
    def setupUi(self, QuizGame):
        self.score = 0
        self.link = 1
        self.ques_dir = {
            1: "Каким был первый полнометражный анимационный фильм?",
            2: "Какого цвета была таблетка, которую \n принимает Нео в фильме “Матрица”?",
            3: "За какой фильм Том Хэнкс получил свою \n первую номинацию на премию “Оскар”?",
            4: "Кто сыграл детектива Рика Декарда \n в фильме “Бегущий по лезвию” (1982)?",
            5: "Этот признанный режиссер, лауреат премии “Оскар”,\n снял фильмы “Делай ноги”, “Бейб: Поросенок в городе” и \n “Безумный Макс: Дорога ярости”.",
            6: "Какие животные воспитывали Маугли в “Книге джунглей”?",
            7: "В каком диснеевском фильме дебютировала Джули Эндрюс?",
            8: "Кто является первой цветной женщиной, \n получившей премию “Оскар” за лучшую женскую роль?",
            9: "Радость, Страх, Гнев, Брезгливость и Печаль \n управляют чьими эмоциями в фильме “Головоломка”?",
            10: "Какой фильм, написанный, снятый и\n спродюсированный Джеймсом Кэмероном, \nстал самым кассовым фильмом своего времени?"
        }
        self.ans_dir = {
            1: {"Покахонтас": "-", "Белоснежка и семь гномов": "+", "Русалочка": "-", "Золушка": "-"},
            2: {"Красный": "+", "Синий": "-", "Зеленый": "-", "Желтый": "-"},
            3: {"Большой": "+", "Форрест Гамп": "-", "Аполлон 13": "-", "Вам письмо": "-"},
            4: {"Джордж Клуни": "-", "Ричард Гир": "-", "Харрисон Форд": "+", "Райан Гослинг": "-"},
            5: {"Дэвид Линч": "-", "Кристофер Нолан": "-", "Стивен Спилберг": "-", "Джордж Миллер": "+"},
            6: {"Лисы": "-", "Приматы": "-", "Волки": "+", "Медведи": "-"},
            7: {"Шрек": "-", "Мэри Поппинс": "+", "Дневники принцессы": "-", "Звуки музыки": "-"},
            8: {"Виола Дэвис": "-", "Керри Вашингтон": "-", "Хэлли Берри": "+", "Реджина Кинг": "-"},
            9: {"Бонни": "-", "Бу": "-", "Энди": "-", "Райли": "+"},
            10: {"Титаник": "+", "Аватар": "-", "Терминатор": "-", "Правдивая ложь": "-"}
        }
        self.res = list(self.ans_dir[self.link].keys())

        self.ans1, self.ans2, self.ans3, self.ans4 = 0, 0, 0, 0
        QuizGame.setObjectName("QuizGame")
        QuizGame.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(QuizGame)
        self.centralwidget.setObjectName("centralwidget")
        self.ques = QtWidgets.QLabel(self.centralwidget)
        self.ques.setGeometry(QtCore.QRect(0, 0, 600, 260))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(12)
        font.setUnderline(False)
        self.ques.setFont(font)
        self.ques.setAutoFillBackground(False)
        self.ques.setStyleSheet("background-color: rgb(97, 97, 97);\n"
"color: rgb(255, 255, 255);\n"
"border-bottom: 2px solid;")
        self.ques.setAlignment(QtCore.Qt.AlignCenter)
        self.ques.setObjectName("ques")
        self.ans_1 = QtWidgets.QPushButton(self.centralwidget)
        self.ans_1.setGeometry(QtCore.QRect(0, 260, 300, 80))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(10)
        self.ans_1.setFont(font)
        self.ans_1.setMouseTracking(True)
        self.ans_1.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.ans_1.setObjectName("ans_1")
        self.ans_2 = QtWidgets.QPushButton(self.centralwidget)
        self.ans_2.setGeometry(QtCore.QRect(300, 260, 300, 80))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(10)
        self.ans_2.setFont(font)
        self.ans_2.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.ans_2.setObjectName("ans_2")
        self.ans_3 = QtWidgets.QPushButton(self.centralwidget)
        self.ans_3.setGeometry(QtCore.QRect(0, 340, 300, 80))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(10)
        self.ans_3.setFont(font)
        self.ans_3.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"color: rgb(255, 255, 255);")
        self.ans_3.setObjectName("ans_3")
        self.ans_4 = QtWidgets.QPushButton(self.centralwidget)
        self.ans_4.setGeometry(QtCore.QRect(300, 340, 300, 80))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(10)
        self.ans_4.setFont(font)
        self.ans_4.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"color: rgb(255, 255, 255);")
        self.ans_4.setObjectName("ans_4")
        self.next_but = QtWidgets.QPushButton(self.centralwidget)
        self.next_but.setGeometry(QtCore.QRect(0, 420, 600, 80))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(20)
        self.next_but.setFont(font)
        self.next_but.setStyleSheet("background-color: rgb(10, 147, 2);\n"
"\n"
"border-color: rgb(0, 0, 0);")
        self.next_but.setObjectName("next_but")
        QuizGame.setCentralWidget(self.centralwidget)

        self.retranslateUi(QuizGame)
        QtCore.QMetaObject.connectSlotsByName(QuizGame)
        self.welcome = QMessageBox(self.centralwidget)
        self.welcome.setWindowTitle("QuizGame")
        self.welcome.setText("Welcome to my first QuizGame!\nPress Start or Quit")
        self.welcome.setStandardButtons(QMessageBox.Apply | QMessageBox.Ok)

        self.clicked()

    def retranslateUi(self, QuizGame):
        _translate = QtCore.QCoreApplication.translate
        QuizGame.setWindowTitle(_translate("QuizGame", "QuizGame"))
        self.ques.setText(_translate("QuizGame", self.ques_dir[self.link]))
        self.ans_1.setText(_translate("QuizGame", self.res[0]))
        self.ans_2.setText(_translate("QuizGame", self.res[1]))
        self.ans_3.setText(_translate("QuizGame", self.res[2]))
        self.ans_4.setText(_translate("QuizGame", self.res[3]))
        self.next_but.setText(_translate("QuizGame", "Next"))

    def clicked(self):
        self.ans_1.clicked.connect(lambda: self.choose_ans(self.ans_1.text()))
        self.ans_2.clicked.connect(lambda: self.choose_ans(self.ans_2.text()))
        self.ans_3.clicked.connect(lambda: self.choose_ans(self.ans_3.text()))
        self.ans_4.clicked.connect(lambda: self.choose_ans(self.ans_4.text()))
        self.next_but.clicked.connect(lambda: self.write())

    def write(self):
        if self.link < 10:
            if self.ans1 == 1:
                if self.ans_dir[self.link][self.ans_1.text()] == "+":
                    self.score += 1
            elif self.ans2 == 1:
                if self.ans_dir[self.link][self.ans_2.text()] == "+":
                    self.score += 1
            elif self.ans3 == 1:
                if self.ans_dir[self.link][self.ans_3.text()] == "+":
                    self.score += 1
            elif self.ans4 == 1:
                if self.ans_dir[self.link][self.ans_4.text()] == "+":
                    self.score += 1
            self.link += 1
            self.res = list(self.ans_dir[self.link].keys())
            self.ques.setText(self.ques_dir[self.link])
            self.ans_1.setText(self.res[0])
            self.ans_2.setText(self.res[1])
            self.ans_3.setText(self.res[2])
            self.ans_4.setText(self.res[3])
            self.ans_1.setStyleSheet("background-color: rgb(74, 74, 74);\n"
                                     "color: rgb(255, 255, 255);")
            self.ans_2.setStyleSheet("background-color: rgb(74, 74, 74);\n"
                                     "color: rgb(255, 255, 255);")
            self.ans_3.setStyleSheet("background-color: rgb(74, 74, 74);\n"
                                     "color: rgb(255, 255, 255);")
            self.ans_4.setStyleSheet("background-color: rgb(74, 74, 74);\n"
                                     "color: rgb(255, 255, 255);")
            self.ans1, self.ans2, self.ans3, self.ans4 = 0, 0, 0, 0
        else:
            self.ques.setText(f"Congrats!!\nYour score is {self.score}")
            self.ans_1.setText("Game Over")
            self.ans_2.setText("Game Over")
            self.ans_3.setText("Game Over")
            self.ans_4.setText("Game Over")



    def choose_ans(self, text):
        if text == self.res[0]:
            self.ans_1.setStyleSheet("background-color: rgb(10, 147, 2);\n"
                                    "color: rgb(0, 0, 0);")
            self.ans_2.setStyleSheet("background-color: rgb(74, 74, 74);\n"
                                     "color: rgb(255, 255, 255);")
            self.ans_3.setStyleSheet("background-color: rgb(74, 74, 74);\n"
                                     "color: rgb(255, 255, 255);")
            self.ans_4.setStyleSheet("background-color: rgb(74, 74, 74);\n"
                                     "color: rgb(255, 255, 255);")
            self.ans1 += 1
        elif text == self.res[1]:
            self.ans_2.setStyleSheet("background-color: rgb(10, 147, 2);\n"
                                    "color: rgb(0, 0, 0);")
            self.ans_1.setStyleSheet("background-color: rgb(74, 74, 74);\n"
                                     "color: rgb(255, 255, 255);")
            self.ans_3.setStyleSheet("background-color: rgb(74, 74, 74);\n"
                                     "color: rgb(255, 255, 255);")
            self.ans_4.setStyleSheet("background-color: rgb(74, 74, 74);\n"
                                     "color: rgb(255, 255, 255);")
            self.ans2 += 1
        elif text == self.res[2]:
            self.ans_3.setStyleSheet("background-color: rgb(10, 147, 2);\n"
                                    "color: rgb(0, 0, 0);")
            self.ans_2.setStyleSheet("background-color: rgb(74, 74, 74);\n"
                                     "color: rgb(255, 255, 255);")
            self.ans_1.setStyleSheet("background-color: rgb(74, 74, 74);\n"
                                     "color: rgb(255, 255, 255);")
            self.ans_4.setStyleSheet("background-color: rgb(74, 74, 74);\n"
                                     "color: rgb(255, 255, 255);")
            self.ans3 += 1
        elif text == self.res[3]:
            self.ans_4.setStyleSheet("background-color: rgb(10, 147, 2);\n"
                                     "color: rgb(0, 0, 0);")
            self.ans_1.setStyleSheet("background-color: rgb(74, 74, 74);\n"
                                     "color: rgb(255, 255, 255);")
            self.ans_3.setStyleSheet("background-color: rgb(74, 74, 74);\n"
                                     "color: rgb(255, 255, 255);")
            self.ans_2.setStyleSheet("background-color: rgb(74, 74, 74);\n"
                                     "color: rgb(255, 255, 255);")
            self.ans4 += 1


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    QuizGame = QtWidgets.QMainWindow()
    ui = Ui_QuizGame()
    ui.setupUi(QuizGame)
    QuizGame.show()
    sys.exit(app.exec_())
